version: "3.8"
services:
  postgres:
    container_name: postgres-bis-lists
    image: postgres:10
    restart: on-failure
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma_password
      POSTGRES_DB: bis-list
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data:delegated

volumes:
  postgres:
